version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466" # database playground
    depends_on:
      - database
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            database: bricabrac
            schema: public
            user: babadmin
            password: XXX
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: true

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: babadmin
      POSTGRES_PASSWORD: XXX
      POSTGRES_DB: bricabrac
